name: GitHub Classroom Workflow
on:
  push:
    branches: [ master, develop ]

env:
  KUBE_HOST: ${{ secrets.KUBE_HOST }}
  KUBE_TOKEN: ${{ secrets.KUBE_TOKEN }}
  
jobs:
  build:
    name: Autograding
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: docker/setup-buildx-action@v2

      # TODO build, publish to docker hub, deploy to k8s
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Publish
        run: |
          docker buildx build --push -t ayjahanmeredova/rsoi-api-gateway:1.0 --platform=linux/amd64 src/gatewayService
          docker buildx build --push -t ayjahanmeredova/rsoi-cars-service:1.0 --platform=linux/amd64 src/carsService
          docker buildx build --push -t ayjahanmeredova/rsoi-rental-service:1.0 --platform=linux/amd64 src/rentalService
          docker buildx build --push -t ayjahanmeredova/rsoi-payment-service:1.0 --platform=linux/amd64 src/paymentService

      - name: Deploy
        run: |
          kubectl config set-cluster rsoi-car-rental-service-cluster --server="$KUBE_HOST" --insecure-skip-tls-verify=true

          kubectl config set-credentials cloud_okteto_com-user --token="$KUBE_TOKEN"

          kubectl config set-context default --cluster=rsoi-car-rental-service-cluster --user=cloud_okteto_com-user --namespace="ayymeredova"

          kubectl config use-context default

          kubectl get pods

          cd k8s

          helm upgrade services ./services-chart

          sleep 50

          
      - name: Run API Tests
        uses: matt-ball/newman-action@master
        with:
          collection: v3/postman/collection.json
          environment: v3/postman/environment.json
          delayRequest: 100
          reporters: '[ "cli" ]'

      - uses: education/autograding@v1
        id: autograder
        continue-on-error: true

      - name: Github auto grader mark
        uses: Romanow/google-sheet-autograder-marker@v1.0
        with:
          google_token: ${{secrets.GOOGLE_API_KEY}}
          sheet_id: "1xkgjUX6Qmk7rdJG-QPOToav-HWWtthJjnShIKnw3oIY"
          homework_number: 4
          user_column: 'D'
          column_offset: 'F'
          mark: "'+"